<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-04-01T22:45:01Z" name="Suite" finished-at="2019-04-01T22:45:31Z" duration-ms="30096">
    <groups>
    </groups>
    <test started-at="2019-04-01T22:45:01Z" name="Opening Facebook Landing Page" finished-at="2019-04-01T22:45:09Z" duration-ms="7824">
      <class name="testcases.FB_LandingPage_Test">
        <test-method signature="Login()[pri:0, instance:testcases.FB_LandingPage_Test@5d8bafa9]" started-at="2019-04-01T15:45:04Z" name="Login" finished-at="2019-04-01T15:45:08Z" duration-ms="4121" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Share what's new] but found [Some Random Text]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Share what's new] but found [Some Random Text]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at testcases.FB_LandingPage_Test.Login(FB_LandingPage_Test.java:35)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
      </class> <!-- testcases.FB_LandingPage_Test -->
    </test> <!-- Opening Facebook Landing Page -->
    <test started-at="2019-04-01T22:45:09Z" name="SuperLeague: Signing in using invalid and invalid email" finished-at="2019-04-01T22:45:31Z" duration-ms="22081">
      <class name="testcases.SignUpPage_Login_Test">
        <test-method signature="LoginToAccount(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testcases.SignUpPage_Login_Test@17a1e4ca]" started-at="2019-04-01T15:45:11Z" name="LoginToAccount" data-provider="getData" finished-at="2019-04-01T15:45:21Z" duration-ms="10201" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://www.superleague.com/login/]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[failedtest@gmail.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[12345678]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginToAccount -->
        <test-method signature="LoginToAccount(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testcases.SignUpPage_Login_Test@17a1e4ca]" started-at="2019-04-01T15:45:21Z" name="LoginToAccount" data-provider="getData" finished-at="2019-04-01T15:45:31Z" duration-ms="10174" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://www.superleague.com/login/]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[buffboyali@gmail.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[messenger]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginToAccount -->
      </class> <!-- testcases.SignUpPage_Login_Test -->
    </test> <!-- SuperLeague: Signing in using invalid and invalid email -->
  </suite> <!-- Suite -->
</testng-results>
